spring:
  datasource:
    initialization-mode: always
    data:
      - classpath:sql/create-concert-domain.sql
      - classpath:sql/create-ticket-domain.sql
      - classpath:sql/create-point-domain.sql
      - classpath:sql/create-payment-domain.sql
      - classpath:sql/create-user-domain.sql
    url: jdbc:mysql://mysql:3306/dev-db?serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  redis:
    host: redis
    port: 6379
    timeout: 2000
    maxTotal: 50
    maxIdle: 10
    minIdle: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#      properties:
#        hibernate:
#          format_sql: true

logging:
  level:
    root: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE