spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test-user
    password:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    maxTotal: 50
    maxIdle: 10
    minIdle: 1
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE