spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;TIME ZONE=UTC
    driverClassName: org.h2.Driver
    username: test-user
    password:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    maxTotal: 50
    maxIdle: 10
    minIdle: 1
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      dataLocations:
        - classpath:sql/create-concert-domain.sql
        - classpath:sql/create-ticket-domain.sql
        - classpath:sql/create-point-domain.sql
        - classpath:sql/create-payment-domain.sql
        - classpath:sql/create-user-domain.sql

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE